import type { LiveConnection, LiveStats } from './monitoring.types';

// Placeholder data so the page renders before live wiring exists. Replace with
// real-time data from the monitoring endpoint / WebSocket.
export const MOCK_LIVE_STATS: LiveStats = {
  inboundActive: 7,
  inboundTotal: 18432,
  outboundActive: 3,
  mailSent: 15290,
  mailReceived: 16871,
  rejected: 1242,
  deferred: 39,
  uptimeSeconds: 327540,
  throughputPerMin: 42,
};

export const MOCK_CONNECTIONS: LiveConnection[] = [
  {
    id: 'c1',
    direction: 'inbound',
    remoteIp: '203.0.113.42',
    remoteHost: 'mail.example.net',
    helo: 'mail.example.net',
    mailFrom: 'newsletter@example.net',
    rcptCount: 2,
    state: 'DATA',
    tls: true,
    bytes: 48211,
    startedAt: Date.now() - 4200,
  },
  {
    id: 'c2',
    direction: 'inbound',
    remoteIp: '198.51.100.9',
    remoteHost: null,
    helo: 'host9.acme.io',
    mailFrom: 'billing@acme.io',
    rcptCount: 1,
    state: 'RCPT',
    tls: true,
    bytes: 1820,
    startedAt: Date.now() - 1500,
  },
  {
    id: 'c3',
    direction: 'outbound',
    remoteIp: '142.250.80.27',
    remoteHost: 'gmail-smtp-in.l.google.com',
    helo: 'mx.cirrusmail.cloud',
    mailFrom: 'noreply@cirrusmail.cloud',
    rcptCount: 1,
    state: 'DATA',
    tls: true,
    bytes: 73140,
    startedAt: Date.now() - 8800,
  },
  {
    id: 'c4',
    direction: 'outbound',
    remoteIp: '40.92.10.16',
    remoteHost: 'outlook-com.olc.protection.outlook.com',
    helo: 'mx.cirrusmail.cloud',
    mailFrom: 'alerts@cirrusmail.cloud',
    rcptCount: 3,
    state: 'MAIL',
    tls: true,
    bytes: 5120,
    startedAt: Date.now() - 600,
  },
  {
    id: 'c5',
    direction: 'inbound',
    remoteIp: '192.0.2.211',
    remoteHost: 'scanner.badactor.example',
    helo: 'localhost',
    mailFrom: null,
    rcptCount: 0,
    state: 'connect',
    tls: false,
    bytes: 0,
    startedAt: Date.now() - 300,
  },
];
