import type { MailRecord } from './mailHistory.types';

// Placeholder delivery history; replace with the message-log endpoint.
export const MOCK_MAIL_HISTORY: MailRecord[] = [
  {
    id: 'm1',
    direction: 'outbound',
    from: 'noreply@cirrusmail.cloud',
    to: 'alice@gmail.com',
    subject: 'Welcome to Cirrus',
    status: 'delivered',
    size: 24110,
    spamScore: 0.2,
    remoteHost: 'gmail-smtp-in.l.google.com',
    timestamp: Date.now() - 120_000,
  },
  {
    id: 'm2',
    direction: 'inbound',
    from: 'newsletter@acme.io',
    to: 'team@cirrusmail.cloud',
    subject: 'Acme monthly digest',
    status: 'received',
    size: 81230,
    spamScore: 1.1,
    remoteHost: 'mail.acme.io',
    timestamp: Date.now() - 360_000,
  },
  {
    id: 'm3',
    direction: 'outbound',
    from: 'billing@cirrusmail.cloud',
    to: 'cfo@partner.net',
    subject: 'Invoice #20451',
    status: 'deferred',
    size: 18240,
    spamScore: null,
    remoteHost: 'mx.partner.net',
    timestamp: Date.now() - 900_000,
  },
  {
    id: 'm4',
    direction: 'inbound',
    from: 'spammer@bad.example',
    to: 'sales@cirrusmail.cloud',
    subject: 'You won a prize!!!',
    status: 'quarantined',
    size: 4096,
    spamScore: 9.8,
    remoteHost: 'unknown.bad.example',
    timestamp: Date.now() - 1_500_000,
  },
  {
    id: 'm5',
    direction: 'outbound',
    from: 'alerts@cirrusmail.cloud',
    to: 'noone@nonexistent.tld',
    subject: 'Disk usage warning',
    status: 'bounced',
    size: 5120,
    spamScore: null,
    remoteHost: 'mx.nonexistent.tld',
    timestamp: Date.now() - 3_600_000,
  },
  {
    id: 'm6',
    direction: 'inbound',
    from: 'noauth@open-relay.example',
    to: 'admin@cirrusmail.cloud',
    subject: 'relay test',
    status: 'rejected',
    size: 0,
    spamScore: null,
    remoteHost: 'open-relay.example',
    timestamp: Date.now() - 7_200_000,
  },
];
